### ISSUE TITLE
Is this project still being worked on?

### ISSUE THREAD

**Issue by WardPearce** [DIMSI-IS/BackROLL#19]

**Comment by nabdoul** [comment]
Hi @WardPearce,
Yes, the project is still ongoing. Currently, our developers are working on implementing a Backroll version to deploy it quickly for developers. The pull request on the cloudstack plugin is ongoing. Our development team needs to implement a few adjustments before proceeding with the pull request.

**Comment by WardPearce** [comment]
Awesome, happy to hear. Looking forward to using this in the future!

**Comment by eddiewang** [comment]
ditto on this. looking forward to testing this plugin! couldn't figure out at first glance how to get this repo to work with our existing cloudstack environment.

**Comment by m-dhellin** [comment]
Hello @WardPearce and @eddiewang,

You can preview the developpement versions of Backroll at [https://github.com/DIMSI-IS/BackROLL/tree/main/compose_project](https://github.com/DIMSI-IS/BackROLL/tree/main/compose_project).

Feel free to open a discussion if you need some updates or if you have any suggestions : [https://github.com/DIMSI-IS/BackROLL/discussions](https://github.com/DIMSI-IS/BackROLL/discussions).
