### ISSUE TITLE
Trouble adding the cloudstack connector secret key

### ISSUE THREAD

**Issue by rajujith** [DIMSI-IS/BackROLL#38]
Backroll version: v0.4.0-alpha-1-25-g50d43bf

The cloudstack connector secret key value changes to the API key value on the first attempt. On updating it again it gets updated to the right value.

**Comment by m-dhellin** [comment]
Hi @rajujith,

We are currently doing some refactoring on the forms so it should be fixed soon.

**Comment by m-dhellin** [comment]
Hi @rajujith,

The pull request is merged.
