### ISSUE TITLE
Blank UI

### ISSUE THREAD

**Issue by sagb** [DIMSI-IS/BackROLL#6]
After successfull installation, the UI is blank (browser requests are listed below). No errors in docker logs. Is there any means for debug?

304 http://server:8080/#/
200 http://server:8080/config.js
200 http://server:8080/js/app.8e4469b4.js
200 http://server:8080/js/chunk-vendors.18e3297e.js
200 http://server:8080/favicon.ico

**Comment by nsaikrishna15** [comment]
same happening for me aswell. passed all the variables properly

**Comment by srekkas** [comment]
Hi, I have blank screen issue too. Do you resolved it?

**Comment by JoffreyLuang** [comment]
Hi @srekkas , blank ui can happens if there's a misconfiguration in env files or issue with SSO. You can have more information on what's happening with f12 console mode in your browser. 
You can also check for logs of container ui and core with command `docker logs container_name`.

**Comment by srekkas** [comment]
> Hi @srekkas , blank ui can happens if there's a misconfiguration in env files or issue with SSO. You can have more information on what's happening with f12 console mode in your browser. You can also check for logs of container ui and core with command `docker logs container_name`.

Got this error. 

dsb-vue-keycloak.umd.js:191 Error: Failure during initialization of keycloak-js adapter
    at dsb-vue-keycloak.umd.js:188:27 {error: 'Timeout when waiting for 3rd party check iframe message.'}

I have https on my keycloak with local signed CA certificate if that helps.
